=== DSpace/DSpace-SVN-Deprecated/dspace/config/item-submission.dtd
<!-- DSpace Custom Item Submission Process definition language -->
<!--                                                           -->
<!-- This DTD defines the format for the DSpace                -->
<!-- 'config/item-submission.xml' configuration file           -->

 <!-- Root element is 'item-submission' -->
 <!ELEMENT item-submission (submission-map, step-definitions, submission-definitions) >

 <!-- 'submission-map' must contain one or more 'name-map' nodes -->
 <!ELEMENT submission-map (name-map+) >
 
 <!ELEMENT name-map EMPTY >
 <!ATTLIST name-map 
           collection-handle CDATA #REQUIRED
           submission-name NMTOKEN #REQUIRED>

 <!-- 'step-definitions' must contain at least one 'step' node -->
 <!-- (The "select collection" step *must* be here)            -->
 <!ELEMENT step-definitions (step+) >
 
 <!ELEMENT step (heading?, processing-class, review-jsp?, xml-ui-class?, workflow-editable?) >
 <!ATTLIST step id NMTOKEN #IMPLIED>
 
 <!ELEMENT heading (#PCDATA) >
 <!ELEMENT processing-class (#PCDATA)>
 <!ELEMENT xml-ui-class (#PCDATA)>
 <!ELEMENT review-jsp (#PCDATA)>
 <!ELEMENT workflow-editable (#PCDATA)>
 
 <!-- 'submission-definitions' must contain at least one       -->
 <!-- 'submission-process' node                                -->
 <!ELEMENT submission-definitions (submission-process+)>
 
 <!ELEMENT submission-process (step+)>
 <!ATTLIST submission-process name NMTOKEN #REQUIRED>

=== DSpace/DSpace-SVN-Deprecated/dspace/config/item-submission-JSPUI.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE item-submission SYSTEM "item-submission.dtd">

<!-- JSP-UI Configurable Submission configuration file  -->

<!-- This XML configuration file allows you to configure the ordering     -->
<!-- and number of the steps that occur in the Item Submission Process.   -->
<item-submission>

 <!-- The process-map maps collection handles to a particular Item         -->
 <!-- Submission Process.  This requires that a collection's name be       -->
 <!-- unique, even within a community. DSpace does however insure that each-->
 <!-- collection's handle is unique.  Process-map provides the means to    -->
 <!-- associate a unique collection name with an Item Submission process.  -->
 <!-- The process-map also provides the special handle "default" (which is -->
 <!-- never a collection), here mapped to "traditional". Any collection    -->
 <!-- which does not appear in this map will be associated with the mapping-->
 <!-- for handle "default".                                                -->
 <submission-map>
   <name-map collection-handle="default" submission-name="traditional" />
 </submission-map>


 
 <!-- The 'step-definitions' allows you to define steps which you may wish -->
 <!-- to "share" amongst multiple submission-item definitions.  In order to-->
 <!-- share the same step definition, you can refer to it by its unique id -->
 <!-- defined in this section.  EVERY 'step' in this section MUST have a   -->
 <!-- unique identifier in the 'id' attribute!                             -->
 <!--                                                                      -->
 <!-- Each <step> REQUIRES the following attributes (@) and properties:    --> 
 <!-- @id       - The unique identifier for this step                      -->
 <!-- <processing-class> - The class which will process all information for-->
 <!--             this step. The class must implement the                  -->
 <!--             'org.dspace.app.webui.submit.JSPStep' interface AND      -->
 <!--             extend 'org.dspace.submit.AbstractProcessingStep'        -->
 <!--             (or one of the org.dspace.submit.step.* classes)         -->
 <!--             This property should reference the full path of the class-->
 <!--			  (e.g. org.dspace.app.webui.submit.MyCustomJSPStep)       -->
 <!--																	   -->
 <!-- The following properties are OPTIONAL for each <step>:			   -->
 <!-- <heading> -    References the message text (from the 				   -->
 <!--			     Messages.properties file) which will be used as this  -->
 <!--			     step's heading in the progress-bar.  If unspecified,  -->
 <!--			     the step does not show up in the Progress Bar.	       -->
 <!-- <review-jsp> - The context path (e.g. /submit/myJSP.jsp) of the JSP  -->
 <!--				 which will give a READ-ONLY view of the users answers -->
 <!--				 for this entire step.  This JSP is used by the        -->
 <!--				 "Verify" step to allow the users to review his/her    -->
 <!--				 for each previous step.  If the <review-jsp> is       -->
 <!--				 unspecified, the user will not be able to review      -->
 <!--				 his/her answers for this <step> in the "Verify" step. -->
 <!-- <workflow-editable> - whether or not this step will appear during the-->
 <!--				 "Edit Metadata" workflow approval process.  This field-->
 <!--				 defaults to TRUE (which means it can be edited during -->
 <!--				 the "Edit Metadata" workflow stage)				   -->
 <!--                                                                      -->
 <!--                                                                      -->
 <step-definitions>
     <!-- The "collection" step is a "special step" which is *REQUIRED* to be-->
     <!-- in this section!  In DSpace, all submitted items must be           -->
     <!-- immediately assigned to a collection. This step ensures that a     -->
     <!-- collection is always selected.  If a user is already submitting    -->
     <!-- from within a Collection (by clicking the "Submit to This          -->
     <!-- Collection" button) then this step will be automatically skipped.  -->
     <!-- In all other cases, this step ensures that the user *first* selects-->
     <!-- a collection!                                                      -->
     <!-- Since this is a "special step", it is *automatically* added at the -->
     <!-- beginning of each 'submission-process' (therefore it should not be -->
     <!-- referenced by any of the below 'submission-process' tags).  Also as-->
     <!-- a special step, it is currently NEVER editable in a workflow.      -->                              
     <step id="collection">
       <heading></heading> <!--can specify heading, if you want it to appear in Progress Bar-->
       <processing-class>org.dspace.app.webui.submit.step.JSPSelectCollectionStep</processing-class>
       <workflow-editable>false</workflow-editable>
     </step>
   
     <!-- The "complete" step is a "special step" which is *REQUIRED* to be-->
     <!-- in this section!  In DSpace, when a submission is completed,       -->
     <!-- a workflow is automatically kicked off (if one exists)             -->
     <!-- This "complete" step performs all backend processing that occurs   -->
     <!-- immediately upon completing the submission.                        -->
     <!-- Since this is a "special step", it is *automatically* added at the -->
     <!-- end of each 'submission-process' (therefore it should not be       -->
     <!-- referenced by any of the below 'submission-process' tags).  Also as-->
     <!-- a special step, it is currently NEVER editable in a workflow.      -->                               
     <step id="complete">
       <heading>jsp.submit.progressbar.complete</heading>
       <processing-class>org.dspace.app.webui.submit.step.JSPCompleteStep</processing-class>
       <workflow-editable>false</workflow-editable>
     </step>
   
   
     <!-- This is the Sample Step which utilizes the JSPSampleStep class-->
     <step id="sample">
            <heading>Sample</heading>
            <processing-class>org.dspace.app.webui.submit.step.JSPSampleStep</processing-class>
            <review-jsp>/submit/sample-review.jsp</review-jsp>
            <workflow-editable>true</workflow-editable>
     </step>
 </step-definitions>

 <!-- The submission-definitions map lays out the detailed definition of   -->
 <!-- all the Item Submission Processes (and the ordering of their steps). -->
 <!-- Each separate "submission-process" has a unique name as an attribute,-->
 <!-- which matches one of the names in the process-map. One named         -->
 <!-- "submit-process" has the name "traditional"; as this name suggests,  -->
 <!-- it is the default item submission process, which gets used when      -->
 <!-- the specified collection has no correspondingly named submit-process.-->
 <!--                                                                      -->
 <!-- Each submit-process contains an ordered set of steps; each step      -->
 <!-- defines one "step" occurring during the process of submitting an     -->
 <!-- item.  A step can either be reference by 'id' (in which case it must -->
 <!-- be defined in <step-definitions> above), or defined completely here. -->
 <!--                                                                      -->
 <!-- If the step is not referred to by 'id', then the <step> REQUIRES the -->
 <!-- following properties are defined:                                    --> 
 <!-- <processing-class> - The class which will process all information for-->
 <!--             this step. The class must implement the                  -->
 <!--             'org.dspace.app.webui.submit.JSPStep' interface AND      -->
 <!--             extend 'org.dspace.submit.AbstractProcessingStep'        -->
 <!--             (or one of the org.dspace.submit.step.* classes)         -->
 <!--             This property should reference the full path of the class-->
 <!--			  (e.g. org.dspace.app.webui.submit.MyCustomJSPStep)       -->
 <!--                                                                      -->
 <!-- The following properties are OPTIONAL for each <step>:			   -->
 <!-- <heading> -    References the message text (from the 				   -->
 <!--			     Messages.properties file) which will be used as this  -->
 <!--			     step's heading in the progress-bar.  If unspecified,  -->
 <!--			     the Step does not show up in the Progress Bar.	       -->
 <!-- <review-jsp> - The context path (e.g. /submit/myJSP.jsp) of the JSP  -->
 <!--				 which will give a READ-ONLY view of the users answers -->
 <!--				 for this entire step.  This JSP is used by the        -->
 <!--				 "Verify" step to allow the users to review his/her    -->
 <!--				 for each previous step.  If the <review-jsp> is       -->
 <!--				 unspecified, the user will not be able to review      -->
 <!--				 his/her answers for this <step> in the "Verify" step. -->
 <!-- <workflow-editable> - whether or not this step will appear during the-->
 <!--				 "Edit Metadata" workflow approval process.  This field-->
 <!--				 defaults to TRUE (which means it can be edited during -->
 <!--				 the "Edit Metadata" workflow stage).  Set to either   -->
 <!--				 "true" or "false".				                       -->
 <!--                                                                      -->
 <submission-definitions>
   
   <!--This "traditional" process defines the DEFAULT item submission process-->
   <submission-process name="traditional">
     
     <!--Uncommment to display the SAMPLE step as your first step-->
     <!--<step id="sample"/>-->
          
     <!--Step 1 will be to gather initial information-->
	  <step>
	    <heading>jsp.submit.progressbar.describe</heading>
	    <processing-class>org.dspace.app.webui.submit.step.JSPInitialQuestionsStep</processing-class>
	    <review-jsp>/submit/review-init.jsp</review-jsp>
